language: go

matrix:
    - include:
        - go: 1.6
        - go: 1.7

notifications:
    email: false

before_install:
    - go get -u github.com/golang/lint/golint

script:
    - golint
    - go test